#!/bin/sh
set -eu

one() {
  paste -sd+ < "$fn" | sed 's/++/\n/g' | sed 's/+*$//g' \
    | bc | sort -n | tail -1
}

two() {
  paste -sd+ < "$fn" | sed 's/++/\n/g' | sed 's/+*$//g' \
    | bc | sort -n | tail -3 | paste -sd+ | bc
}

fn="$1"
[ ! -f "$fn" ] && exit
one
two
